version: "3.9"

services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - AWS_DEFAULT_REGION=eu-central-1
    volumes:
      - "./.localstack:/var/lib/localstack"

  express:
    build: .
    container_name: express-api
    volumes:
      - "./cors.json:/tmp/cors.json"
    ports:
      - "3000:3000"
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_REGION=eu-central-1
      - S3_ENDPOINT=http://localstack:4566
      - S3_BUCKET=local-bucket
    depends_on:
      localstack:
        condition: service_healthy
    command: ["npm", "start"]
